"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import os

# Load environment variables from .env file
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / '.env'
load_dotenv(ENV_PATH)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is already defined above


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. Generate one and add it to backend/.env "
        "(never commit it, never hardcode a fallback here)."
    )

# Dedicated key for encrypting stored client-database connection passwords at rest
# (databases.fields.EncryptedCharField). Deliberately separate from SECRET_KEY so
# rotating one never silently affects the other. Generate with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": "5/min",
        "register": "5/hour",
        "otp_request": "5/min",
        "otp_verify": "5/min",
        "execute_query": "30/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    # Add these lines to include username in JWT token
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    # Add username to JWT token claims
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "session",  # Added session app
    "user",     # Added user app
    "databases", # Added databases app
    "llm_agent",
    "evals",     # Text-to-SQL evaluation suite

    "rest_framework_simplejwt.token_blacklist",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'user': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# ---------------------------------------------------------------------------
# Text-to-SQL: guardrails, confidence, sample DB, dev auth
# ---------------------------------------------------------------------------

# Set DJANGO_ENV=production on real deploys.
ENVIRONMENT = os.getenv('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'

# Fail closed: production must never run with DEBUG on.
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured(
        "DEBUG must be False when DJANGO_ENV=production. Refusing to start."
    )

# Native password login + create_dev_user JWTs, gated on three independent
# conditions: non-production, DEBUG on, and DEV_AUTH_BYPASS opted in.
DEV_AUTH_BYPASS = (
    not IS_PRODUCTION
    and DEBUG
    and os.getenv('DEV_AUTH_BYPASS', 'False') == 'True'
)
if DEV_AUTH_BYPASS:
    import warnings
    warnings.warn(
        "DEV_AUTH_BYPASS is ON: native password auth and create_dev_user are active. "
        "This must never be enabled in production.",
        stacklevel=1,
    )

# Include the raw EXPLAIN plan JSON (table/column names, filters) in the
# execute_query response. Always the caller's own DB; off in production by default.
EXPOSE_EXPLAIN_PLAN = os.getenv(
    'EXPOSE_EXPLAIN_PLAN',
    'False' if IS_PRODUCTION else 'True',
) == 'True'

# QueryExecutionLog: when False, store only a fingerprint, not the SQL text or NL
# question (both can hold user literals). Off in production by default, on in dev.
AUDIT_LOG_STORE_SQL = os.getenv(
    'AUDIT_LOG_STORE_SQL',
    'False' if IS_PRODUCTION else 'True',
) == 'True'

# Connection URL for the seeded sample database (eval suite + demo). Local
# Postgres or Supabase; tables live in a dedicated schema, never `public`.
SAMPLE_DB_URL = os.getenv('SAMPLE_DB_URL', '')
SAMPLE_DB_SCHEMA = os.getenv('SAMPLE_DB_SCHEMA', 't2s_sample')
SAMPLE_DB_READONLY_ROLE = os.getenv('SAMPLE_DB_READONLY_ROLE', 'text2sql_ro')

# Guardrail defaults; each rule is toggleable and callers may override per request.
GUARDRAIL_DEFAULTS = {
    'single_statement': True,
    'syntax_valid': True,
    'block_ddl': True,
    'block_writes': True,          # honoured only when the target DB is read_only
    'enforce_row_limit': True,
    'max_rows': 1000,
    'max_subquery_depth': True,
    'max_depth': 3,
    'explain_row_estimate': True,
    'max_scan_rows': 5_000_000,
}

# Weights for confidence.compose(). Signals that did not run are renormalised out.
CONFIDENCE_WEIGHTS = {
    'syntax_valid': 0.15,
    'back_translation': 0.35,
    'sanity_checks': 0.20,
    'multi_query_agreement': 0.15,
    'schema_coverage': 0.15,
}

# Below this back-translation alignment the query is flagged low-confidence.
BACK_TRANSLATION_FLAG_THRESHOLD = float(os.getenv('BACK_TRANSLATION_FLAG_THRESHOLD', '0.55'))

# Default model names for the provider layer (llm_agent/llm_providers.py).
SQL_GENERATION_MODEL = os.getenv('SQL_GENERATION_MODEL', 'gemini-2.0-flash')
VERIFICATION_MODEL = os.getenv('VERIFICATION_MODEL', 'gemini-2.0-flash')

# Multi-query agreement in the /api/llm/query/ pipeline costs one extra
# generation + execution per request. Off by default; a request may still opt in
# per call with deep=true. Back-translation (one call) always runs.
VERIFICATION_MULTI_QUERY = os.getenv('VERIFICATION_MULTI_QUERY', 'False') == 'True'

# Privacy-first defaults — both OFF unless opted in (dev .env.example sets True).

# Fall back to another LLM provider when the requested one has no key. Off -> a
# missing key raises instead of quietly sending prompts to a different vendor.
LLM_ALLOW_PROVIDER_FALLBACK = os.getenv('LLM_ALLOW_PROVIDER_FALLBACK', 'False') == 'True'

# Include real sample column values in the SQL-generation prompt — helps match
# filter literals but sends row data to the external provider.
LLM_ALLOW_SAMPLE_VALUES_IN_PROMPT = os.getenv('LLM_ALLOW_SAMPLE_VALUES_IN_PROMPT', 'False') == 'True'